---
bibliography: references.bib
---

# Linking basic research to clinical interventions {background-image="https://www.tees.ac.uk/Images/CommonImages/prospectus/PG/course_images/psychology.jpg" background-color="black"}

# What is basic clinical research?

"any type of psychological research investigating processes that are involved in the development and/or maintenance of psychopathology across any level of explanation (e.g., biological, cognitive, behavioral)" [@EhringEtAl2022]

- Could also be called fundamental or core research

## Why does basic research matter?

Information about core psychological processes is essential to:

-  clarify how particular psychological disorders develop, are maintained, and ultimately how they may be prevented

- guide treatment development if the psychopathology process of interest can be modeled with sufficient detail


:::{.aside}
[@ForsythZvolensky2001].
:::

## How much are treatments informed by research?

- Only 23% of treatments showed a very strong link between basic research and the development of the intervention, and further 20% showed a strong link 

:::{.aside}
[@EhringEtAl2022].
:::

## Some of the issues with translating cinical psychology research into treatment/intervention 

- Lack of stability and replicability of basic research findings

- Lack of basic studies establishing causality before moving to testing complex clinical intervention

- Fat-handed interventions and easy-to-vary theories

- Imbalance between research focused on efficacy compared to research on mediators, mechanisms of change, and moderators

## Lack of stability and replicability of basic research findings

Research findings in clinical psychology are not as reliable as assumed, due to:

- Use of unreliable measures
- Underpowered samples
- Publication bias
- Lack of transparency in research practices

## Lack of basic studies establishing causality before moving to testing complex clinical intervention

- Targets for intervention are often identified via correlational studies

- Once identified, they are often tested in applied studies using novel or modified interventions

- This misses two important steps:
1. Is the target a *cause* of psychopathology?
1. *How* do we modify interventions to change this target?

> These questions need to be answered through basic research.

## Overly-broad interventions and easy-to-vary theories

- Establishing causality is difficult in psychological research

- Interventions often lack precision in terms of what they are targeting

- Can lack clear theoretical framework of the mechanisms of change and how psychological processes (e.g., attention, perception, memory, emotion) are involved

- Theories are often easy to vary, and can be used to explain almost any outcome

## Imbalance between research focused on efficacy compared to research on mechanisms of change

- In order to improve treatments, we need to understand *how* and *why* they work, not just *if* they work

- To get a complete understanding of a treatment, we need to understand: Efficacy, Mediators, Mechanisms of change, Moderators

- This requires whole programs of research, not just a single study

# Takeaways:

- Too many clinical studies are focused on efficacy, and not enough on mediators, mechanisms of change.

- Too many efficacy studies are focused on complex interventions, and theories are often "elastic" to explain any outcome. 

