<!DOCTYPE html>
<html lang="en"><head>
<script src="moderation_files/libs/clipboard/clipboard.min.js"></script>
<script src="moderation_files/libs/quarto-html/tabby.min.js"></script>
<script src="moderation_files/libs/quarto-html/popper.min.js"></script>
<script src="moderation_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="moderation_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="moderation_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="moderation_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.25">

  <meta name="author" content="Dr Christopher Wilson">
  <title>Moderation Designs</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="moderation_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="moderation_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="moderation_files/libs/revealjs/dist/theme/quarto-534cd8e3a96973385dffff3f4709048d.css">
  <link rel="stylesheet" href="include/style.css">
  <link href="moderation_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="moderation_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="moderation_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="moderation_files/libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="moderation_files/libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="moderation_files/libs/revealjs/plugin/reveal-drop/drop-runtime.css" rel="stylesheet">
  <link href="moderation_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <link href="moderation_files/libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet">

  <script src="moderation_files/libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>

  <script src="moderation_files/libs/viz-1.8.2/viz.js"></script>

  <link href="moderation_files/libs/DiagrammeR-styles-0.2/styles.css" rel="stylesheet">

  <script src="moderation_files/libs/grViz-binding-1.0.11/grViz.js"></script>

</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Moderation Designs</h1>
  <p class="subtitle">DClin Research Methods 1</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Dr Christopher Wilson 
</div>
        <p class="quarto-title-affiliation">
            Teesside University
          </p>
    </div>
</div>

</section>
<section id="recap" class="slide level2 smaller">
<h2>Recap</h2>
<div class="fragment fade-in-then-semi-out smaller">
<ul>
<li>Thinking about more than outcomes. Designing studies to answer more <strong>specific research questions / think about process</strong>.
<ul>
<li>“Why is this happening?”</li>
<li>“What is the mechanism?”</li>
</ul></li>
</ul>
</div>
<div class="fragment fade-in-then-semi-out">
<ul>
<li>Thinking beyond significance testing. Using <strong>confidence intervals and effect sizes</strong> to interpret results.
<ul>
<li>“How big is the effect?”</li>
<li>“What is the range of plausible values?”</li>
</ul></li>
</ul>
</div>
<div class="fragment fade-in-then-semi-out">
<ul>
<li>Thinking about the relationship between variables. Modelling relationships between variables using regression.
<ul>
<li>“Does <strong>Predictor Variable</strong> (e.g.&nbsp;Treatment Group, Avoidance, Trait) predict <strong>Outcome Variable</strong> (e.g.&nbsp;Wellbeing, Depression, Behaviour)?”</li>
<li>“How much variance is explained by the model?”</li>
</ul></li>
</ul>
</div>
</section>
<section id="last-week-and-the-week-before" class="slide level2">
<h2>Last week and the week before</h2>
<div class="callout callout-none no-icon callout-style-simple">
<div class="callout-body">
<div class="callout-content">
<ul>
<li>Thinking about the relationship between variables. Modelling relationships between variables using regression.
<ul>
<li>“Does <strong>Predictor Variable</strong> (e.g.&nbsp;Treatment Group, Avoidance, Trait) predict <strong>Outcome Variable</strong> (e.g.&nbsp;Wellbeing, Depression, Behaviour)?”</li>
<li>“How much variance is explained by the model?”</li>
</ul></li>
</ul>
</div>
</div>
</div>
<ul>
<li><p>We looked at building regression models based on our research questions and hypotheses.</p></li>
<li><p>This allowed us to consider the contribution of multiple predictors to an outcome variable.</p></li>
</ul>
</section>
<section id="today" class="slide level2">
<h2>Today</h2>
<div class="callout callout-none no-icon callout-style-simple">
<div class="callout-body">
<div class="callout-content">
<ul>
<li>Thinking about more than outcomes. Designing studies to answer more <strong>specific research questions / think about process</strong>.
<ul>
<li>“Why is this happening?”</li>
<li>“What is the mechanism?”</li>
</ul></li>
</ul>
</div>
</div>
</div>
<blockquote>

<ul>
<li>We will be looking at how we can use regression to model <strong>interactions</strong> between variables.</li>
</ul>

</blockquote>
<blockquote>

<ul>
<li>We will also be looking at how we can use regression to model <strong>moderation</strong> of relationships between variables.</li>
</ul>

</blockquote>
</section>
<section id="what-are-interactions-1" class="slide level2">
<h2>What are interactions? #1</h2>
<ul>
<li>Interactions are when the outcome variable is influenced by the interaction between two or more predictor variables.</li>
</ul>
<p>For example, if we are looking at whether <em>Time in counselling</em> and <em>Rapport level with clinician</em> predict <em>General Wellbeing</em>.</p>
<ul>
<li><p>Without the interaction, we consider the effect of <em>Time in counselling</em> or <em>Rapport level with clinician</em> on <em>General Wellbeing</em>.</p></li>
<li><p>With the interaction, we consider the effect of <em>Time in counselling</em> on <em>General Wellbeing</em> at different levels of <em>Rapport level with clinician</em> (or vice versa).</p></li>
</ul>
</section>
<section>
<section id="note-all-assumptions-of-multiple-regression-also-apply-to-interactions-and-moderation." class="title-slide slide level1 center">
<h1>Note: All assumptions of multiple regression also apply to interactions and moderation.</h1>

</section>
<section id="how-do-we-check-for-interactions" class="slide level2 smaller">
<h2>How do we check for interactions?</h2>
<ul>
<li><p>We can check if there is an interaction between predictor variables when we build our regression model.</p></li>
<li><p>We do this by adding a term to our model that represents the interaction between the predictor variables.</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="annotated-cell-1"><pre class="sourceCode numberSource r code-annotation-code number-lines code-with-copy code-annotated"><code class="sourceCode r"><span id="annotated-cell-1-1"><a href="#annotated-cell-1-1"></a><span class="co"># model1 without interactions</span></span>
<span id="annotated-cell-1-2"><a href="#annotated-cell-1-2"></a></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-1" data-target-annotation="1" onclick="event.preventDefault();" href="">1</a><span id="annotated-cell-1-3" class="code-annotation-target"><a href="#annotated-cell-1-3"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data =</span> modData, generalWellbeing <span class="sc">~</span> timeInCounselling <span class="sc">+</span> rapportLevel)</span>
<span id="annotated-cell-1-4"><a href="#annotated-cell-1-4"></a></span>
<span id="annotated-cell-1-5"><a href="#annotated-cell-1-5"></a><span class="co"># model1 with interactions</span></span>
<span id="annotated-cell-1-6"><a href="#annotated-cell-1-6"></a></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-1" data-target-annotation="2" onclick="event.preventDefault();" href="">2</a><span id="annotated-cell-1-7" class="code-annotation-target"><a href="#annotated-cell-1-7"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data =</span> modData, generalWellbeing <span class="sc">~</span> timeInCounselling <span class="sc">*</span> rapportLevel)</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-1" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-1" data-code-lines="3" data-code-annotation="1">This model does not include an interaction between timeInCounselling and rapportLevel. This is because we used the + symbol to separate the predictor variables.</span>
</dd>
<dt data-target-cell="annotated-cell-1" data-target-annotation="2">2</dt>
<dd>
<span data-code-cell="annotated-cell-1" data-code-lines="7" data-code-annotation="2">This model does include an interaction between timeInCounselling and rapportLevel. This is because we used the * symbol to separate the predictor variables.</span>
</dd>
</dl>
</div>
</div>
</section>
<section id="interpreting-interactions-in-regression-1" class="slide level2 smaller">
<h2>Interpreting interactions in regression #1</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="annotated-cell-2"><pre class="sourceCode numberSource r code-annotation-code number-lines code-with-copy"><code class="sourceCode r"><span id="annotated-cell-2-1"><a href="#annotated-cell-2-1"></a><span class="co"># model1 with interactions</span></span>
<span id="annotated-cell-2-2"><a href="#annotated-cell-2-2"></a></span>
<span id="annotated-cell-2-3"><a href="#annotated-cell-2-3"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data =</span> modData, generalWellbeing <span class="sc">~</span> timeInCounselling <span class="sc">*</span> rapportLevel)</span>
<span id="annotated-cell-2-4"><a href="#annotated-cell-2-4"></a></span>
<span id="annotated-cell-2-5"><a href="#annotated-cell-2-5"></a><span class="fu">summary</span>(model1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = generalWellbeing ~ timeInCounselling * rapportLevel, 
    data = modData)

Residuals:
    Min      1Q  Median      3Q     Max 
-17.497  -9.119  -0.234   6.125  37.896 

Coefficients:
                               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                    17.28817    3.14907   5.490 3.28e-07 ***
timeInCounselling               0.15174    0.41507   0.366  0.71548    
rapportLevel                   -0.41300    0.30045  -1.375  0.17246    
timeInCounselling:rapportLevel  0.15338    0.04031   3.805  0.00025 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 11.36 on 96 degrees of freedom
Multiple R-squared:  0.2763,    Adjusted R-squared:  0.2537 
F-statistic: 12.22 on 3 and 96 DF,  p-value: 7.701e-07</code></pre>
</div>
</div>
</section>
<section id="interpreting-interactions-in-regression-2" class="slide level2">
<h2>Interpreting interactions in regression #2</h2>
<ul>
<li><p>We can see that the overall model is significant</p></li>
<li><p>We can see that the interaction between timeInCounselling and rapportLevel is significant</p></li>
<li><p>We can see that the main effects of timeInCounselling and rapportLevel are not significant</p></li>
<li><p>In models where the interaction is significant, we should not interpret the main effects of the predictor variables (even when they are significant).</p></li>
</ul>
</section>
<section id="interpreting-interactions-in-regression-3" class="slide level2">
<h2>Interpreting interactions in regression #3</h2>
<ul>
<li>We can look at the <strong>simple slopes</strong> of the interaction.</li>
</ul>

<img data-src="moderation_files/figure-revealjs/unnamed-chunk-4-1.png" width="960" class="r-stretch"></section>
<section id="interpreting-interactions-in-regression-4" class="slide level2">
<h2>Interpreting interactions in regression #4</h2>
<ul>
<li><p>We can further test this interaction by calculating range of values where the interaction is significant.</p></li>
<li><p>We can do this using the <code>rockchalk</code> package. We will do it our moderation example later.</p></li>
</ul>
</section>
<section id="thinking-about-interactions" class="slide level2">
<h2>Thinking about interactions</h2>
<ul>
<li><p>We can see that the relationship between timeInCounselling and generalWellbeing is different at different levels of rapportLevel.</p></li>
<li><p>This means that the variables are interacting with each other to predict the outcome variable.</p></li>
</ul>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p>If we plan to test for interactions, we need to make sure that we have enough power to do so. It is more than just adding another predictor, as interaction effects tend to be <strong>much</strong> weaker than main effects.</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="moderation-designs" class="title-slide slide level1 center">
<h1>Moderation designs</h1>

</section>
<section id="what-are-moderation-designs" class="slide level2">
<h2>What are moderation designs?</h2>
<ul>
<li><p>Moderation designs are when the relationship between two variables is moderated by a third variable.</p></li>
<li><p>This is similar to an interaction, but we are stating our theoretical model about the relationship between the variables in a more specific way.</p></li>
<li><p>For example, we might be interested in whether the relationship between Trait Anxiety and Depression is moderated by Avoidance.</p></li>
<li><p>We are specifically stating that we believe Trait Anxiety predicts Depression, but that their relationship is different at different levels of Avoidance.</p></li>
</ul>
</section></section>
<section>
<section id="so-moderation-is-just-an-interaction-effect" class="title-slide slide level1 center">
<h1>So moderation is just an interaction effect?</h1>
<p>Statistically, yes. Theoretically, no.</p>
<p>From a theory perspective, we are stating that we believe that the relationship between two variables is moderated by a third variable.</p>
</section>
<section id="diagram-of-moderation-design" class="slide level2">
<h2>Diagram of moderation design</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="grViz html-widget html-fill-item" id="htmlwidget-fe3dc638d9e1e0722840" style="width:960px;height:480px;"></div>
<script type="application/json" data-for="htmlwidget-fe3dc638d9e1e0722840">{"x":{"diagram":"\n\tdigraph moderation_model { \n\t  # Nodes  \n\t  node [shape = rectangle, fontname = Arial, fontsize=9]\n\t  iv    [pos = \"-1,1!\", label = \"Time in\ncounselling\"]\n\t  blank [pos =  \"0,1!\", label = \"\", width = 0.001, height = 0.001]\n\t  mod   [pos =  \"0,2!\", label = \"Rapport\nlevel\"]\n\t  dv    [pos =  \"1,1!\", label = \"General\nwellbeing\"]\n\t    \n\t  # Hide moderator edges\n\t  { rank = same; blank mod }\n\t  \n\t  # Edges\n\t  edge [fontname = Arial, fontsize=8]\n\t  mod -> blank\n\t  iv -> blank [dir = none]\n\t  blank -> dv [minlen = 1]\n\n\t  # Graph\n\t  graph [layout = neato, overlap = true, outputorder = edgesfirst]\n}","config":{"engine":"dot","options":null}},"evals":[],"jsHooks":[]}</script>
</div>
</div>
</section>
<section id="when-should-we-use-moderation-designs" class="slide level2">
<h2>When should we use moderation designs?</h2>
<ul>
<li><p>We should use moderation designs when we have a theoretical reason to believe that the relationship between two variables is moderated by a third variable.</p></li>
<li><p>This should come from a good understanding of the literature and the theory behind the variables.</p></li>
<li><p>We should not use moderation designs “just to see what happens”. The statistical test alone does not <strong>prove</strong> the existence of the theoretical relationship.</p></li>
</ul>
</section>
<section id="how-do-we-check-for-moderation" class="slide level2">
<h2>How do we check for moderation?</h2>
<ul>
<li><p>The first step is to build a regression model that includes the main effects and the interaction between the two predictor variables (this is the same as interaction that we covered earlier).</p></li>
<li><p>If the interaction is significant, we can then visualise the interaction using simple slopes (same as what we did earlier).</p></li>
<li><p>We can then calculate the range of values of the moderator variable where the interaction is significant.</p></li>
</ul>
</section>
<section id="moderation-example" class="slide level2">
<h2>Moderation example</h2>
<ul>
<li><p>Let’s imagine that we theorise that the relationship between <em>Time in counselling</em> and <em>General Wellbeing</em> is moderated by <em>Rapport level</em>.</p></li>
<li><p>We want to know at which levels of <em>Rapport level</em> the relationship between <em>Time in counselling</em> and <em>General Wellbeing</em> is significant.</p></li>
<li><p>We also want to know the direction of the relationship between <em>Time in counselling</em> and <em>General Wellbeing</em> at different levels of <em>Rapport level</em>.</p></li>
</ul>
</section>
<section id="moderation-example-2" class="slide level2">
<h2>Moderation example #2</h2>
<p>The regression model is the same as the one we used for interactions.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="annotated-cell-3"><pre class="sourceCode numberSource r code-annotation-code number-lines code-with-copy code-annotated"><code class="sourceCode r"><span id="annotated-cell-3-1"><a href="#annotated-cell-3-1"></a><span class="co"># model1 with interactions</span></span>
<span id="annotated-cell-3-2"><a href="#annotated-cell-3-2"></a></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-3" data-target-annotation="1" onclick="event.preventDefault();" href="">1</a><span id="annotated-cell-3-3" class="code-annotation-target"><a href="#annotated-cell-3-3"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data =</span> modData, generalWellbeing <span class="sc">~</span> timeInCounselling <span class="sc">*</span> rapportLevel)</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-3" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-3" data-code-lines="3" data-code-annotation="1">This model includes an interaction between timeInCounselling and rapportLevel. We know this because we used the * symbol to separate the predictor variables.</span>
</dd>
</dl>
</div>
</div>
</section>
<section id="testing-the-moderation-effect" class="slide level2 scrollable">
<h2>Testing the moderation effect</h2>
<p>Testing at which levels of <em>Rapport level</em> the relationship between <em>Time in counselling</em> and <em>General Wellbeing</em> is significant.</p>
<p>Step 1: Run the regression model:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href=""></a><span class="co"># model1 with interactions</span></span>
<span id="cb2-2"><a href=""></a></span>
<span id="cb2-3"><a href=""></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data =</span> modData, generalWellbeing <span class="sc">~</span> timeInCounselling <span class="sc">*</span> rapportLevel)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="testing-the-moderation-effect-2" class="slide level2 scrollable">
<h2>Testing the moderation effect #2</h2>
<p>Step 2: Plot the interaction:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href=""></a><span class="co"># model1 with interactions</span></span>
<span id="cb3-2"><a href=""></a></span>
<span id="cb3-3"><a href=""></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data =</span> modData, generalWellbeing <span class="sc">~</span> timeInCounselling <span class="sc">*</span> rapportLevel)</span>
<span id="cb3-4"><a href=""></a></span>
<span id="cb3-5"><a href=""></a><span class="co"># using the rockchalk package</span></span>
<span id="cb3-6"><a href=""></a></span>
<span id="cb3-7"><a href=""></a><span class="fu">library</span>(rockchalk)</span>
<span id="cb3-8"><a href=""></a></span>
<span id="cb3-9"><a href=""></a><span class="co"># use the plotSlopes() function</span></span>
<span id="cb3-10"><a href=""></a></span>
<span id="cb3-11"><a href=""></a>ps <span class="ot">&lt;-</span> <span class="fu">plotSlopes</span>(model1, <span class="at">plotx =</span> <span class="st">"timeInCounselling"</span>, <span class="at">modx =</span> <span class="st">"rapportLevel"</span>, <span class="at">interval =</span> <span class="st">"confidence"</span>, <span class="at">modxVals =</span> <span class="st">"std.dev"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href=""></a>ps</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>$call
plotSlopes.lm(model = model1, plotx = "timeInCounselling", modx = "rapportLevel", 
    modxVals = "std.dev", interval = "confidence")

$newdata
    timeInCounselling rapportLevel      fit       lwr      upr
1           0.0000000        -2.64 18.37848 11.026008 25.73095
2           0.3846154        -2.64 18.28110 11.260845 25.30136
3           0.7692308        -2.64 18.18373 11.491611 24.87585
4           1.1538462        -2.64 18.08636 11.717677 24.45504
5           1.5384615        -2.64 17.98898 11.938290 24.03968
6           1.9230769        -2.64 17.89161 12.152542 23.63068
7           2.3076923        -2.64 17.79424 12.359341 23.22913
8           2.6923077        -2.64 17.69686 12.557361 22.83637
9           3.0769231        -2.64 17.59949 12.745000 22.45398
10          3.4615385        -2.64 17.50212 12.920322 22.08391
11          3.8461538        -2.64 17.40474 13.080993 21.72849
12          4.2307692        -2.64 17.30737 13.224237 21.39050
13          4.6153846        -2.64 17.20999 13.346794 21.07320
14          5.0000000        -2.64 17.11262 13.444943 20.78030
15          5.3846154        -2.64 17.01525 13.514590 20.51591
16          5.7692308        -2.64 16.91787 13.551490 20.28426
17          6.1538462        -2.64 16.82050 13.551607 20.08939
18          6.5384615        -2.64 16.72313 13.511587 19.93467
19          6.9230769        -2.64 16.62575 13.429271 19.82224
20          7.3076923        -2.64 16.52838 13.304065 19.75269
21          7.6923077        -2.64 16.43101 13.137056 19.72496
22          8.0769231        -2.64 16.33363 12.930810 19.73645
23          8.4615385        -2.64 16.23626 12.688938 19.78358
24          8.8461538        -2.64 16.13888 12.415585 19.86218
25          9.2307692        -2.64 16.04151 12.114982 19.96804
26          9.6153846        -2.64 15.94414 11.791127 20.09715
27         10.0000000        -2.64 15.84676 11.447610 20.24592
28         10.3846154        -2.64 15.74939 11.087544 20.41124
29         10.7692308        -2.64 15.65202 10.713570 20.59046
30         11.1538462        -2.64 15.55464 10.327895 20.78139
31         11.5384615        -2.64 15.45727  9.932351 20.98219
32         11.9230769        -2.64 15.35990  9.528451 21.19134
33         12.3076923        -2.64 15.26252  9.117446 21.40760
34         12.6923077        -2.64 15.16515  8.700369 21.62993
35         13.0769231        -2.64 15.06778  8.278078 21.85747
36         13.4615385        -2.64 14.97040  7.851288 22.08951
37         13.8461538        -2.64 14.87303  7.420594 22.32546
38         14.2307692        -2.64 14.77565  6.986498 22.56481
39         14.6153846        -2.64 14.67828  6.549423 22.80714
40         15.0000000        -2.64 14.58091  6.109726 23.05209
41          0.0000000         4.94 15.24797 10.313337 20.18259
42          0.3846154         4.94 15.59774 10.890307 20.30518
43          0.7692308         4.94 15.94752 11.463997 20.43104
44          1.1538462         4.94 16.29730 12.033890 20.56070
45          1.5384615         4.94 16.64707 12.599367 20.69478
46          1.9230769         4.94 16.99685 13.159683 20.83402
47          2.3076923         4.94 17.34663 13.713941 20.97931
48          2.6923077         4.94 17.69640 14.261057 21.13175
49          3.0769231         4.94 18.04618 14.799731 21.29263
50          3.4615385         4.94 18.39596 15.328402 21.46351
51          3.8461538         4.94 18.74573 15.845218 21.64625
52          4.2307692         4.94 19.09551 16.348017 21.84300
53          4.6153846         4.94 19.44529 16.834332 22.05624
54          5.0000000         4.94 19.79506 17.301455 22.28867
55          5.3846154         4.94 20.14484 17.746566 22.54311
56          5.7692308         4.94 20.49462 18.166961 22.82227
57          6.1538462         4.94 20.84439 18.560343 23.12844
58          6.5384615         4.94 21.19417 18.925157 23.46318
59          6.9230769         4.94 21.54395 19.260837 23.82706
60          7.3076923         4.94 21.89372 19.567913 24.21953
61          7.6923077         4.94 22.24350 19.847914 24.63909
62          8.0769231         4.94 22.59328 20.103115 25.08344
63          8.4615385         4.94 22.94305 20.336214 25.54989
64          8.8461538         4.94 23.29283 20.550030 26.03563
65          9.2307692         4.94 23.64261 20.747278 26.53794
66          9.6153846         4.94 23.99238 20.930434 27.05433
67         10.0000000         4.94 24.34216 21.101670 27.58265
68         10.3846154         4.94 24.69194 21.262847 28.12103
69         10.7692308         4.94 25.04171 21.415536 28.66789
70         11.1538462         4.94 25.39149 21.561045 29.22194
71         11.5384615         4.94 25.74127 21.700464 29.78207
72         11.9230769         4.94 26.09104 21.834695 30.34739
73         12.3076923         4.94 26.44082 21.964488 30.91715
74         12.6923077         4.94 26.79060 22.090466 31.49073
75         13.0769231         4.94 27.14037 22.213148 32.06760
76         13.4615385         4.94 27.49015 22.332971 32.64733
77         13.8461538         4.94 27.83993 22.450300 33.22956
78         14.2307692         4.94 28.18970 22.565444 33.81397
79         14.6153846         4.94 28.53948 22.678665 34.40030
80         15.0000000         4.94 28.88926 22.790188 34.98833
81          0.0000000        12.52 12.11745  6.158021 18.07688
82          0.3846154        12.52 12.91438  7.224345 18.60441
83          0.7692308        12.52 13.71131  8.284898 19.13772
84          1.1538462        12.52 14.50823  9.338797 19.67767
85          1.5384615        12.52 15.30516 10.385000 20.22532
86          1.9230769        12.52 16.10209 11.422277 20.78190
87          2.3076923        12.52 16.89902 12.449180 21.34885
88          2.6923077        12.52 17.69594 13.464019 21.92787
89          3.0769231        12.52 18.49287 14.464835 22.52090
90          3.4615385        12.52 19.28980 15.449394 23.13020
91          3.8461538        12.52 20.08672 16.415202 23.75824
92          4.2307692        12.52 20.88365 17.359564 24.40774
93          4.6153846        12.52 21.68058 18.279688 25.08147
94          5.0000000        12.52 22.47750 19.172862 25.78215
95          5.3846154        12.52 23.27443 20.036683 26.51218
96          5.7692308        12.52 24.07136 20.869310 27.27341
97          6.1538462        12.52 24.86829 21.669699 28.06687
98          6.5384615        12.52 25.66521 22.437745 28.89268
99          6.9230769        12.52 26.46214 23.174302 29.74998
100         7.3076923        12.52 27.25907 23.881056 30.63708
101         7.6923077        12.52 28.05599 24.560314 31.55168
102         8.0769231        12.52 28.85292 25.214742 32.49110
103         8.4615385        12.52 29.64985 25.847131 33.45257
104         8.8461538        12.52 30.44678 26.460208 34.43334
105         9.2307692        12.52 31.24370 27.056518 35.43089
106         9.6153846        12.52 32.04063 27.638350 36.44291
107        10.0000000        12.52 32.83756 28.207724 37.46739
108        10.3846154        12.52 33.63448 28.766385 38.50258
109        10.7692308        12.52 34.43141 29.315830 39.54699
110        11.1538462        12.52 35.22834 29.857333 40.59934
111        11.5384615        12.52 36.02527 30.391975 41.65856
112        11.9230769        12.52 36.82219 30.920669 42.72372
113        12.3076923        12.52 37.61912 31.444191 43.79405
114        12.6923077        12.52 38.41605 31.963199 44.86889
115        13.0769231        12.52 39.21297 32.478251 45.94770
116        13.4615385        12.52 40.00990 32.989824 47.02998
117        13.8461538        12.52 40.80683 33.498325 48.11533
118        14.2307692        12.52 41.60376 34.004104 49.20341
119        14.6153846        12.52 42.40068 34.507462 50.29390
120        15.0000000        12.52 43.19761 35.008660 51.38656

$modxVals
(m-sd)    (m) (m+sd) 
 -2.64   4.94  12.52 

$col
     (m-sd)         (m)      (m+sd) 
    "black"      "blue" "darkgreen" 

$lty
(m-sd)    (m) (m+sd) 
     1      2      3 

$fancy
$fancy$col
     (m-sd)         (m)      (m+sd) 
    "black"      "blue" "darkgreen" 

$fancy$lty
(m-sd)    (m) (m+sd) 
     1      2      3 

$fancy$lwd
(m-sd)    (m) (m+sd) 
     2      2      2 


attr(,"class")
[1] "plotSlopes" "rockchalk" </code></pre>
</div>
</div>
<img data-src="moderation_files/figure-revealjs/unnamed-chunk-8-1.png" width="960" class="r-stretch"></section>
<section id="testing-the-moderation-effect-3" class="slide level2 scrollable">
<h2>Testing the moderation effect #3</h2>
<p>Step 3: Test the range of values where the interaction is significant:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href=""></a><span class="co"># model1 with interactions</span></span>
<span id="cb6-2"><a href=""></a></span>
<span id="cb6-3"><a href=""></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data =</span> modData, generalWellbeing <span class="sc">~</span> timeInCounselling <span class="sc">*</span> rapportLevel)</span>
<span id="cb6-4"><a href=""></a></span>
<span id="cb6-5"><a href=""></a><span class="co"># using the rockchalk package</span></span>
<span id="cb6-6"><a href=""></a></span>
<span id="cb6-7"><a href=""></a><span class="fu">library</span>(rockchalk)</span>
<span id="cb6-8"><a href=""></a></span>
<span id="cb6-9"><a href=""></a><span class="co"># use the plotSlopes() function</span></span>
<span id="cb6-10"><a href=""></a></span>
<span id="cb6-11"><a href=""></a>ps <span class="ot">&lt;-</span> <span class="fu">plotSlopes</span>(model1, <span class="at">plotx =</span> <span class="st">"timeInCounselling"</span>, <span class="at">modx =</span> <span class="st">"rapportLevel"</span>, <span class="at">interval =</span> <span class="st">"confidence"</span>, <span class="at">modxVals =</span> <span class="st">"std.dev"</span>) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href=""></a><span class="co"># use the testSlopes() function</span></span>
<span id="cb7-2"><a href=""></a></span>
<span id="cb7-3"><a href=""></a>ts <span class="ot">&lt;-</span> <span class="fu">testSlopes</span>(ps)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Values of rapportLevel OUTSIDE this interval:
        lo         hi 
-10.828550   3.537184 
cause the slope of (b1 + b2*rapportLevel)timeInCounselling to be statistically significant</code></pre>
</div>
</div>
<img data-src="moderation_files/figure-revealjs/unnamed-chunk-9-1.png" width="960" class="r-stretch"></section>
<section id="testing-the-moderation-effect-4" class="slide level2 scrollable">
<h2>Testing the moderation effect #4</h2>
<p>Step 4: Visualise the results:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href=""></a><span class="co"># model1 with interactions</span></span>
<span id="cb9-2"><a href=""></a></span>
<span id="cb9-3"><a href=""></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data =</span> modData, generalWellbeing <span class="sc">~</span> timeInCounselling <span class="sc">*</span> rapportLevel)</span>
<span id="cb9-4"><a href=""></a></span>
<span id="cb9-5"><a href=""></a><span class="co"># using the rockchalk package</span></span>
<span id="cb9-6"><a href=""></a></span>
<span id="cb9-7"><a href=""></a><span class="fu">library</span>(rockchalk)</span>
<span id="cb9-8"><a href=""></a></span>
<span id="cb9-9"><a href=""></a><span class="co"># use the plotSlopes() function</span></span>
<span id="cb9-10"><a href=""></a></span>
<span id="cb9-11"><a href=""></a>ps <span class="ot">&lt;-</span> <span class="fu">plotSlopes</span>(model1, <span class="at">plotx =</span> <span class="st">"timeInCounselling"</span>, <span class="at">modx =</span> <span class="st">"rapportLevel"</span>, <span class="at">interval =</span> <span class="st">"confidence"</span>, <span class="at">modxVals =</span> <span class="st">"std.dev"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="moderation_files/figure-revealjs/unnamed-chunk-10-1.png" width="960"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href=""></a><span class="co"># use the testSlopes() function</span></span>
<span id="cb10-2"><a href=""></a></span>
<span id="cb10-3"><a href=""></a>ts <span class="ot">&lt;-</span> <span class="fu">testSlopes</span>(ps)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Values of rapportLevel OUTSIDE this interval:
        lo         hi 
-10.828550   3.537184 
cause the slope of (b1 + b2*rapportLevel)timeInCounselling to be statistically significant</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href=""></a><span class="co"># plot the range of significant values</span></span>
<span id="cb12-2"><a href=""></a></span>
<span id="cb12-3"><a href=""></a><span class="fu">plot</span>(ts)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="moderation_files/figure-revealjs/unnamed-chunk-10-2.png" width="960"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="how-do-we-interpret-the-moderation-effect" class="slide level2">
<h2>How do we interpret the moderation effect?</h2>
<ul>
<li><p>We can see that the relationship between <em>Time in counselling</em> and <em>General Wellbeing</em> is significant levels of <em>Rapport level</em> outside of -10.8 and 3.54.</p></li>
<li><p>However, the <em>Rapport level</em> scale does not actually go below 0. So we can say that the relationship between <em>Time in counselling</em> and <em>General Wellbeing</em> is significant when <em>Rapport level</em> is above 3.54.</p></li>
<li><p>We can look at the first interaction plot to see the direction of the relationship between <em>Time in counselling</em> and <em>General Wellbeing</em> at increasing levels of <em>Rapport level</em>.</p></li>
</ul>
</section>
<section id="summary" class="slide level2">
<h2>Summary</h2>
<ul>
<li><p>We can use regression to model interactions between predictor variables.</p></li>
<li><p>We can also use regression to model moderation of relationships between predictor variables.</p></li>
<li><p>Moderations are just a specific type of interaction. They are based on specific theoretical models about the relationship between variables.</p></li>
<li><p>We can use the <code>rockchalk</code> package to test for interactions and moderation and plot them.</p></li>
</ul>

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="logo.jpg" class="slide-logo"></p>
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="moderation_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="moderation_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="moderation_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="moderation_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="moderation_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="moderation_files/libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="moderation_files/libs/revealjs/plugin/multiplex/socket.io.js"></script>
  <script src="moderation_files/libs/revealjs/plugin/multiplex/multiplex.js"></script>
  <script src="moderation_files/libs/revealjs/plugin/reveal-drop/drop-runtime.js"></script>
  <script src="moderation_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="moderation_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="moderation_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="moderation_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="moderation_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'multiplex': {"secret":"17339195454777741510","id":"0b19bf18debb28ba","url":"https://reveal-multiplex.glitch.me/"},
'drop': {"button":true,"shortcut":"]","engine":"webr","webr":{"packages":["tidyverse"]},"pyodide":{"packages":[]}},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 20,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, RevealDrop, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    

    <script>

      // htmlwidgets need to know to resize themselves when slides are shown/hidden.

      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current

      // slide changes (different for each slide format).

      (function () {

        // dispatch for htmlwidgets

        function fireSlideEnter() {

          const event = window.document.createEvent("Event");

          event.initEvent("slideenter", true, true);

          window.document.dispatchEvent(event);

        }

    

        function fireSlideChanged(previousSlide, currentSlide) {

          fireSlideEnter();

    

          // dispatch for shiny

          if (window.jQuery) {

            if (previousSlide) {

              window.jQuery(previousSlide).trigger("hidden");

            }

            if (currentSlide) {

              window.jQuery(currentSlide).trigger("shown");

            }

          }

        }

    

        // hookup for slidy

        if (window.w3c_slidy) {

          window.w3c_slidy.add_observer(function (slide_num) {

            // slide_num starts at position 1

            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);

          });

        }

    

      })();

    </script>

    

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>