---
bibliography: references.bib
---

# Open Science {background-image="https://images.unsplash.com/photo-1457369804613-52c61a468e7d" background-color="black"}



## What is open and reproducable research?

- Reproducible research is the idea that research is published with their hypotheses, research plan, materials, data and software code so that others can try to replicate the results and verify the findings.

- Studies are pre-registered, so that researchers can see if the study was conducted as planned and the results support the researchers' original hypotheses.

## Why Reproducable Research?

- One of the major limitations of clinical research can be lack of transparency and reproducibility

- Linked to the "easy to vary" problem

- Linked to the "underpowered" problem

- Linked to the "publication bias" problem

- Linked to the "file drawer" problem

## How does open research help address these problems? {.smaller}

- Researchers outline their goals and theories before they begin their research, so that they can be held accountable for their results.

- Sample sizes are determined before the study begins, so that the study is adequately powered to detect the effect size of interest.

- Researchers are encouraged to make all of their results available, regardless of whether the results are statistically significant (where possible).

- Materials, data and code are made available, so that others can try to replicate the results and verify the findings.

## How to make your research reproducable?  {.smaller}

- Pre-register your study
    - [Open Science Framework](https://osf.io/)
    - [Prospero](https://www.crd.york.ac.uk/prospero/)
    - [AsPredicted](https://aspredicted.org/)
- Conduct a power anaysis before you begin your study
    - [G*Power](http://www.gpower.hhu.de/en.html)
    - [Webpower](https://webpower.psychstat.org/wiki/Main_Page)
    - R, SPSS etc.

- Update your registration with any changes to your study and explain why you made the changes

- After your study has been completed, upload your materials, data and code to a repository
    - [Open Science Framework](https://osf.io/)
    - [Figshare](https://figshare.com/)
    - [Zenodo](https://zenodo.org/)
    - [Dryad](https://datadryad.org/)
    - [Dataverse](https://dataverse.org/)
    - [Harvard Dataverse](https://dataverse.harvard.edu/)
    - [OpenICPSR](https://www.openicpsr.org/openicpsr/)
    - [OpenNeuro](https://openneuro.org/)
    - [OpenfMRI](https://openfmri.org/)

# Takeaways:

- Open research increases the transparency of research  

- In doing so, it also helps to address some of the problems in clinical research